Milestone3: Bootstrap columns and borders
Abhi-1725/Newsweek-clone pull request #4
Opened 2021-04-17 08:40 UTC by Abhi-1725

We added the following to milestone 2:

- Create these sections of the website for the 3 screen sizes
- Completed the remaining sections after milestone2

2021-04-17 15:36 UTC, SajjadAhmad14 commented on newsweek.css
> +} */
Remove inline comments

2021-04-17 15:37 UTC, SajjadAhmad14 commented on newsweek.css
> +} */
Remove inline comments.

2021-04-17 15:37 UTC, SajjadAhmad14 commented on newsweek.css
> +} */
Remove inline comments.

2021-04-17 16:28 UTC, Abhi-1725 commented on newsweek.css
> +} */
I have removed the inline comments from the CSS file.

2021-04-17 16:29 UTC, Abhi-1725 commented on newsweek.css
> +} */
I have removed the inline comments from the CSS file.

2021-04-17 16:29 UTC, Abhi-1725 commented on newsweek.css
> +} */
I have removed the inline comments from the CSS file.

2021-04-17 16:33 UTC, SajjadAhmad14 requested changes
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello, you have been doing a tremendous job so far :ok_hand:
## But there are some changes to make in order to get your project approved.

- [x]  README does not include the instructions to run the project locally, also the live link is broken. Please fix that.
- [x]  Please include files in gitignore which are not used e.g vscode.
- [x] Please remove commented code from CSS file.  
- [ ] You should group multiple CSS classes if they have the same rules. Always try to follow the DRY rule.
- [ ] Each title in the magazine and Editor's pick section uses a hx tag and has a link. The title on the hover shows text decoration.
- [x] Navbar is broken on Laptop 1024px screen.
![broken-nav](https://user-images.githubusercontent.com/35504149/115118842-b4bfbf80-9fbe-11eb-8485-f62bf946dd8a.png)

- [x] Orignal page has two columns in each row on tablet viewport in Editor's pick section, but your page has four columns. Kindly fix it!
- [ ] SUBSCRIBE button in the navbar is broken on small mobile screen size. Moreover, the login icon has two more small icons attached. Please fix it!
![broken-icon](https://user-images.githubusercontent.com/35504149/115119188-880ca780-9fc0-11eb-85f1-f5b07192bec0.png)
- [ ] Sponsored Insight section is missing an image with a link on each story on the medium and small screen sizes.
### Main newspaper sections (US, World, etc.):
- [x] Each image have a link.
- [x] Each title uses a hx tag and have a link.
### Subscribe / Newsletter 
- [x] Subscribe section should have a grey background.
- [x] Each section title uses a hx tag 
- [x] Please make Subscribe and Newsletter sections exactly the same as the original on medium and small screen sizes.

# Optional
- [ ] You can use a mock like [this](https://techsini.com/multi-mockup/index.php) to add screenshots of your project on different screen sizes. 

### Happy Coding!

## You can always connect with me on slack ( @Sajjad Ahmad ).

2021-04-17 22:08 UTC, Berabjesus requested changes
## Status: CHANGES REQUIRED :warning: :construction:
Hey, @Abhi-1725  and @P-Rutkowski you have done an awesome job so far. Great to see that you have worked on some of the requested features by the previous TSE.

### However, based on the previous review, you still do have a few changes to carry out before you proceed so please take a look at the things you have to work on below.

## readme related
- [ ] README still does not include the instructions to run the project locally. Include some terminal commands (like `git clone --repo--`) so a non-technical user can read, understand and clone your project locally. 
- [ ] The live demo link does not work.
- [ ] .vscode should not appear in the project if it's properly added to `.gitignore` file. Use `.vscode/`

## HTML
- [ ] Each title in the magazine and Editor's pick section uses a hx tag and has a link. The title on the hover shows text decoration. (see comment below)
- [ ] Navbar is still broken on Laptop 1024px screen. 
![image](https://user-images.githubusercontent.com/64360974/115127567-23f9db80-9fe0-11eb-9806-2cdbf64f2b83.png)

- [ ] Editors pick section should have two columns in tablet mode. Yours is not responsive.
#### original 👇 
![image](https://user-images.githubusercontent.com/64360974/115127622-8521af00-9fe0-11eb-8391-0de9bfeb9c3c.png)
#### yours 👇 
![image](https://user-images.githubusercontent.com/64360974/115127636-a08cba00-9fe0-11eb-85cb-d46be5481180.png)

### Main newspaper sections (US, World, etc.):
- [ ] Each image should have a link.
- [ ] Each title should use a hx tag and should have a link.

### Subscribe / Newsletter
- [ ] Subscribe section should have a grey background.
- [ ]  Each section title uses a hx tag
- [ ] Please make Subscribe and Newsletter sections exactly the same as the original on medium and small screen sizes. It looks a bit messy at the moment.

## optional
- [ ] The navbar should be fixed to the top.

### **❗ You have one (1) remaining review. As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), when you reach to the limit of 3 code reviews and your project was not approved, you will need to repeat the project. If you think that the code review was not fair, you can [request a second-opinion using this form.](https://airtable.com/shrmBIv6cXYrq4Fgv)**

#### **If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help** 
**HAPPY CODING :computer:[Bereket Beshane](https://bereketababu.me)** | [LinkedIn](https://linkedin.com/in/bereketbeshane) | [GitHub](https://github.com/Berabjesus)

2021-04-17 22:08 UTC, Berabjesus commented on index.html
> +              <a href="#" class="text-dark fw-bold fs-6 red-underline text-decoration-none">On His Way Out, Trump Trashes America—and the GOP</a>
- [ ]  This  anchor tag should be a hx tag and has a link. Something like ` <h1><a href="#">link</a></h1>`

2021-04-17 22:08 UTC, Berabjesus commented on index.html
> +            <a href="#" class="card-text text-dark fw-bold fs-5 text-decoration-none">Indiana Homeless Man Chooses to Be Arrested to Avoid Cold Weather</a>
- [ ]  The text content should use a hx tag and has a link. Something like ` <h1><a href="#">link</a></h1>`

2021-04-17 22:08 UTC, Berabjesus commented on index.html
> +            <img src="img/homeless.JPG" class="img-17 img-fluid" alt="homeless" width="400" height="300">
- [ ]  This image tag should have a link.

2021-04-19 02:58 UTC, Abhi-1725 commented on index.html
> +            <a href="#" class="card-text text-dark fw-bold fs-5 text-decoration-none">Indiana Homeless Man Chooses to Be Arrested to Avoid Cold Weather</a>
I have used bootstrap classes instead of headline tag,  as this is bootstrap oriented.

2021-04-19 08:17 UTC, mricanho approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello @Abhi-1725 @P-Rutkowski, good job on your milestone #3! 🔥 

You worked hard in all the instructions that the previous Code Reviewers give you👍🏽 

Now you can merge this branch 🚀 

You can contact me on slack if you have any questions, just search for me as @ Miguel Ricaño.

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

2021-04-19 09:38 UTC, merged